general:
  name: 0.1_sanity_check
  seed: 493
  train_data_path: data/sanitycheck.txt

gptconfig:
  block_size: 1024
  vocab_size: 50304
  n_layer: 12
  n_head: 12
  n_embd: 768
  dropout: 0.0
  bias: True